/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Users {
  created_at: Timestamp
  email: string
  full_name: string | null
  id: number
  password: string
  updated_at: Timestamp
}

export interface DB {
  users: Users
}
